### ISSUE TITLE
[BUG]:  Can't add in Droid-ify

### ISSUE THREAD

**Issue by aicynide** [C10udburst/fdroid#1]
### Description of the bug

.

### Steps To Reproduce

.

### Additional Information

.

**Comment by C10udburst** [comment]
![Screenshot_20240915-221527_Droid-ify](https://github.com/user-attachments/assets/09380ef8-abd6-4122-8adc-4e5d15d95513)
 
cant repro, please give logcat

**Comment by aicynide** [comment]
Fix URL  
Correct - https://c10udburst.github.io/fdroid/repo/#!
